version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: ideahub-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8180
    ports:
      - "8180:8180"
    command: start-dev --http-port=8180
    depends_on:
      - postgres
    networks:
      - ideahub-network

  postgres:
    image: postgres:15
    container_name: ideahub-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - ideahub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideahub-backend
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/ideahub
      KEYCLOAK_URL: http://keycloak:8180
      KEYCLOAK_REALM: ideahub
      KEYCLOAK_CLIENT_ID: ideahub-backend
      KEYCLOAK_CLIENT_SECRET: your-client-secret
      FRONTEND_URL: http://localhost:5000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - ideahub-network

volumes:
  postgres_data:

networks:
  ideahub-network:
    driver: bridge