resilience4j:
  ratelimiter:
    instances:
      ideas-read:
        limit-for-period: 1000
        limit-refresh-period: 60s
        timeout-duration: 1s
      ideas-write:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 2s
      votes-write:
        limit-for-period: 500
        limit-refresh-period: 60s
        timeout-duration: 1s
      comments-write:
        limit-for-period: 200
        limit-refresh-period: 60s
        timeout-duration: 1s
  
  circuitbreaker:
    instances:
      ideas-service:
        register-health-indicator: true
        sliding-window-size: 100
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
      
      database:
        register-health-indicator: true
        sliding-window-size: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-rate-threshold: 60
        slow-call-duration-threshold: 5s

  retry:
    instances:
      database:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.sql.SQLException
          - org.springframework.dao.DataAccessException